cycle/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cycle.Models
{
    public class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public DateTime PublishDate { get; set; }
        public string Content { get; set; }
        public string PhotoUrl { get; set; }
    }
}

cycle/Areas/Admin/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using cycle.Data;
using cycle.Helpers;
using cycle.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace cycle.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<NewController> _logger;
        private readonly IWebHostEnvironment _env;

        public NewController(ILogger<NewController> logger, AppDbContext context, IWebHostEnvironment env)
        {
            _logger = logger;
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            var news = _context.News.OrderByDescending(x => x.Id).ToList();
            return View(news);
        }

        public IActionResult Error()
        {

            return View();
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(string title, string userName, string content, IFormFile photo)
        {
            News news = new News();
            news.PhotoUrl = ImageHelper.UploadSinglePhoto(photo, _env);
            news.UserName = userName;
            news.Content = content;
            news.PublishDate = DateTime.Now;
            news.Title = title;
            _context.News.Add(news);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int Id)
        {
            var detail = _context.News.FirstOrDefault(x => x.Id == Id);
            if (detail == null)
            {
                return RedirectToAction(nameof(Error));
            }
            return View(detail);
        }
        public IActionResult Delete(int Id)
        {
            var delete = _context.News.FirstOrDefault(x => x.Id == Id);
            return View(delete);
        }
        [HttpPost]
        public IActionResult Delete(News news)
        {
            var delete = _context.News.FirstOrDefault(x => x.Id == news.Id);
            _context.News.Remove(delete);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int Id)
        {
            var update = _context.News.FirstOrDefault(x => x.Id == Id);
            if (update.Id == null)
            {
                return RedirectToAction(nameof(Error));
            }
            return View(update);
        }
        [HttpPost]
        public IActionResult Update(News m, IFormFile photo)
        {
            var news = _context.News.FirstOrDefault(x => x.Id == m.Id);
            if (news == null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (photo != null)
            {
                news.PhotoUrl = ImageHelper.UploadSinglePhoto(photo, _env);
            }

            news.Title = m.Title;
            news.Content = m.Content;
            news.PublishDate = DateTime.Now;
            news.UserName = m.UserName;
            _context.News.Update(news);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

cycle/Areas/Admin/Views/New/Create.cshtml
@model News
<form class="container-xl" method="post" enctype="multipart/form-data">
    <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Title</span>
        <input type="text" name="title" class="form-control" aria-label="Sizing example input"
            aria-describedby="inputGroup-sizing-lg">
    </div>
    <br>
    <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">User Name </span>
        <input type="text" name="userName" class="form-control" aria-label="Sizing example input"
            aria-describedby="inputGroup-sizing-lg">
    </div>
    <div class="form-group">
        <label class="form-label"></label>
        <textarea id="editor1" class="form-control" name="content"></textarea>
    </div>
    <div class="input-group">
        <input type="file" class="form-control" name="photo" id="inputGroupFile04"
            aria-describedby="inputGroupFileAddon04" aria-label="Upload">
        <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Button</button>
    </div>
</form>








@section Scripts{
    <script src="https://cdn.ckeditor.com/4.20.1/standard/ckeditor.js"></script>

    <script>
        CKEDITOR.replace('editor1');
    </script>
}

cycle/Areas/Admin/Views/New/Delete.cshtml
@model News
<div class="container ">
    <div class="row">
        <div class="col-lg-8 m-auto">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Are you sure</h5>
                    <p>@Model.Title is deleted</p>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <form method="post">
                            <input type="hidden" name="Id " value="@Model.Id" />
                            <input type="submit" value="Deleted" class="btn btn-outline-danger" />
                        </form>
                        <a class="btn btn-outline-info" href="/admin/prodact/">Gencel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

cycle/Areas/Admin/Views/New/Detail.cshtml
@model News

<div id="main-content" class="blog-page">
    <div class="container">
        <div class="row clearfix">
<a href="/admin/new/index" class="btn btn-primary w-100"> Back </a>
            <div class="col-lg-8 col-md-12 left-box">
                <div class="card single_post">
                    <div class="body">
                        <div class="img-post">
                            <img class="d-block img-fluid w-100" src="@Model.PhotoUrl" alt="First slide">
                        </div>
                        <h3><b>@Model.Title</b></h3>
                        <p>
                            @Html.Raw(Model.Content)
                        </p>
                    </div>
                </div>
                <div class="card">
                    <div class="header">
                        <h2>User </h2>
                    </div>
                    <div class="body">
                        <ul class="comment-reply list-unstyled">
                            <li class="row clearfix">
                                <div class="icon-box col-md-2 col-4"><img class="img-fluid img-thumbnail"
                                        src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Awesome Image">
                                </div>
                                <div class="text-box col-md-10 col-8 p-l-0 p-r0">
                                    <h5 class="m-b-0">@Model.UserName</h5>
                                    <ul class="list-inline">
                                        <li><a>@Model.PublishDate</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

cycle/Areas/Admin/Views/New/Index.cshtml
@model List<News>


<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                <a href="/admin/New/create">Create</a>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#Id</th>
                            <th>Photo</th>
                            <th>Title</th>
                            <th>Content</th>
                            <th>Publish Date </th>
                            <th>
                                Parametr
                            </th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#Id</th>
                            <th>Photo</th>
                            <th>Title</th>
                            <th>Content</th>
                            <th>Publish Date </th>

                            <th>
                                Parametr
                            </th>

                        </tr>
                    </tfoot>
                    <tbody>
                        @* *@
                        @foreach (var news in Model)
                        {
                            <tr>

                                <th>@news.Id</th>
                                <th>
                                    <img src="@news.PhotoUrl" alt="" width="100" srcset="">
                                </th>
                                <th>
                                    @news.Title
                                </th>

                                <th>@Html.Raw(news.Content.Substring(0,10))...</th>
                                <th>
                                    @news.PublishDate.ToString("dd MM yyyy")
                                </th>
                                <th>
                                    <a href="/admin/New/Detail/@news.Id" class="btn btn-danger"> Deteil </a>
                                    <a href="/admin/new/delete/@news.Id" class="btn btn-secondary"> Delete </a>
                                    <a href="/admin/new/update/@news.Id" class="btn btn-info">Update</a>
                                </th>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

cycle/Areas/Admin/Views/New/Update.cshtml
@model News

<form method="post" enctype="multipart/form-data" asp-controller="New" asp-action="Update">
    <div class="form-group">
        <label for="Title">Title</label>
        <input type="text" class="form-control" id="Title" name="Title" value="@Model.Title">
    </div>
    <div class="form-group">
        <label for="UserName">User</label>
        <input type="text" class="form-control" id="UserName" name="UserName" value="@Model.UserName">
    </div>
    <div class="form-group">
        <label for="Content">Content</label>
        <textarea name="Content" id="editor1" cols="30" rows="10">@Model.Content</textarea>
    </div>
    <div class="card mb-6">
        <div class="card-body">
            <div class="form-group">
                <img class="img-fluid mb-4" src="@Model.PhotoUrl" />
                <input type="file" class="form-control" name="photo" />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

@section Scripts{
    <script src="https://cdn.ckeditor.com/4.20.1/standard/ckeditor.js"></script>

    <script>
        CKEDITOR.replace('editor1');
    </script>
}