cycle/Models/Prodact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace cycle.Models
{
    public class Prodact
    {

        public int Id { get; set; }

        public string Name { get; set; }
        public string Content { get; set; }

        public string PhotoUrl { get; set; }
        public Decimal Price { get; set; }
    }
}

cycle/Areas/Admin/Controllers/ProdactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using cycle.Data;
using cycle.Helpers;
using cycle.Models;
using cycle.VievModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace cycle.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProdactController : Controller
    {
        private readonly ILogger<ProdactController> _logger;
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ProdactController(ILogger<ProdactController> logger, AppDbContext context, IWebHostEnvironment env)
        {
            _logger = logger;
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            var prodact = _context.Prodacts.ToList();
            var comment = _context.Comments.OrderByDescending(x => x.Id).ToList();

            MessageVM messageVm = new MessageVM()
            {
                Prodacts = prodact
                ,
                Comments = comment

            };
            return View(messageVm);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]

        public IActionResult Create(string name, string content, Decimal price, IFormFile photo)
        {
            var path = "/uploads/" + Guid.NewGuid() + photo.FileName;
            using (var fileStream = new FileStream(_env.WebRootPath + path, FileMode.Create))
            {
                photo.CopyTo(fileStream);
            }
            Prodact prodact = new Prodact();
            prodact.Name = name;
            prodact.Content = content;
            prodact.Price = price;
            prodact.PhotoUrl = path;
            _context.Prodacts.Add(prodact);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deteil(int id)
        {
            var deteil = _context.Prodacts.FirstOrDefault(x => x.Id == id);
            if (deteil == null)
            {
                return NotFound();
            }
            return View(deteil);
        }

        //??delete method
        public IActionResult Delete(int id)
        {
            var delete = _context.Prodacts.FirstOrDefault(x => x.Id == id);
            return View(delete);
        }

        [HttpPost]
        public IActionResult Delete(Prodact prodact)
        {
            var prodactDelete = _context.Prodacts.FirstOrDefault(x => x.Id == prodact.Id);
            if (prodactDelete == null)
            {
                return NotFound();
            }
            _context.Prodacts.Remove(prodactDelete);
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int Id)
        {
            var update = _context.Prodacts.FirstOrDefault(x => x.Id == Id);
            if (update == null)
            {
                return NotFound();
            }
            return View(update);
        }
        [HttpPost]
        public IActionResult Update(Prodact prodact, IFormFile photo)
        {
            var existingProdact = _context.Prodacts.Find(prodact.Id);
            if (existingProdact == null)
            {
                return NotFound();
            }
            if (photo != null)
            {
                existingProdact.PhotoUrl = ImageHelper.UploadSinglePhoto(photo, _env);
            }
            existingProdact.Name = prodact.Name;
            existingProdact.Price = prodact.Price;
            existingProdact.Content = prodact.Content;
            _context.Prodacts.Update(existingProdact);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

cycle/Areas/Admin/Views/Prodact/Create.cshtml
<form method="post" enctype="multipart/form-data" class="container">
    <div class="form-group">
        <div class="input-group input-group-lg">
            <span class="input-group-text" id="inputGroup-sizing-lg">Name</span>
            <input type="text" name="name" class="form-control" aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-lg">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="price"
                aria-label="Dollar amount (with dot and two decimal places)">
            <span class="input-group-text">$</span>
            <span class="input-group-text">0.00</span>
        </div>
    </div>
    <div class="form-floating form-group">
        <textarea class="form-control" name="content" placeholder="Leave a comment here" id="floatingTextarea2"
            style="height: 100px"></textarea>
        <label for="floatingTextarea2">Comments</label>
    </div>

    <div class="input-group">
        <input type="file" class="form-control" name="photo" id="inputGroupFile04"
            aria-describedby="inputGroupFileAddon04" aria-label="Upload">
        <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Button</button>
    </div>
</form>

cycle/Areas/Admin/Views/Prodact/Delete.cshtml
@model Prodact
<div class="container ">
    <div class="row">
        <div class="col-lg-8 m-auto">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Are you sure</h5>
                    <p>@Model.Name is deleted</p>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <form method="post">
                            <input type="hidden" name="Id " value="@Model.Id" />
                            <input type="submit" value="Deleted" class="btn btn-outline-danger" />
                        </form>
                        <a class="btn btn-outline-info" href="/admin/prodact/">Gencel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

cycle/Areas/Admin/Views/Prodact/Deteil.cshtml
@model Prodact

<div class="container align-items-center justify-content-center text-center ">
    <div class="card mb-3 align-items-center justify-content-center " style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@Model.PhotoUrl" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Name :  <b>@Model.Name</b></h5>
                    <p class="card-text"> <b>Description : </b> @Model.Content </p>
                    <p class="card-text">Price : <small class="text-muted text-center">@Model.Price.</small></p>
                </div>
            </div>
        </div>
    </div>
</div>

cycle/Areas/Admin/Views/Prodact/Index.cshtml
@model MessageVM
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">
                    <a href="/admin/prodact/create">Create</a>
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#Id</th>
                                <th>Photo</th>
                                <th>Name</th>
                                <th>Content</th>
                                <th>Salary</th>
                                <th>Parametir</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#Id</th>
                                <th>Photo</th>
                                <th>Name</th>
                                <th>Content</th>
                                <th>Salary</th>
                                <th>Parametir</th>

                            </tr>
                        </tfoot>
                        <tbody>
                            @* *@
                            @foreach (var prodact in Model.Prodacts)
                            {
                                <tr>

                                    <th>@prodact.Id</th>
                                    <th>
                                        <img src="@prodact.PhotoUrl" alt="" width="100" srcset="">
                                    </th>
                                    <th>
                                        @prodact.Name
                                    </th>
                                    <th>
                                        @prodact.Content
                                    </th>
                                    <th>@prodact.Price</th>
                                    <th>
                                        <a href="/admin/prodact/delete/@prodact.Id" class="btn  btn-danger">Delete</a>
                                        <a href="/admin/prodact/deteil/@prodact.Id" class="btn  btn-outline-info">Deteil</a>
                                        <a href="/admin/prodact/Update/@prodact.Id" class="btn  btn-warning">Update</a>
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>

    </div>

cycle/Areas/Admin/Views/Prodact/Update.cshtml
@model Prodact

<form method="post" enctype="multipart/form-data" asp-controller="Prodact" asp-action="Update">
    <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
    </div>
    <div class="form-group">
        <label for="Content">Content</label>
        <textarea class="form-control" id="Content editor1" name="Content">@Model.Content</textarea>
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input type="text" class="form-control" id="Price" name="Price" value="@Model.Price">
    </div>
    <div class="card mb-6">
        <div class="card-body">
            <div class="form-group">
                <img class="img-fluid mb-4" src="@Model.PhotoUrl" />
                <input type="file" class="form-control" name="photo" />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

@section Scripts{
    <script src="https://cdn.ckeditor.com/4.20.1/standard/ckeditor.js"></script>

    <script>
        CKEDITOR.replace('editor1');
    </script>
}